#!/bin/bash

ip link set dev eth0 up
ip addr add 200.2.255.131/26 dev eth0


ip link set dev eth1 up
ip addr add 200.2.255.193/26 dev eth1


#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 200.2.255.64/26 via 200.2.255.131
#ip route add 200.2.255.0/26 via 200.2.255.131
#ip route add 192.168.198.128/25 via 200.2.255.131

#routage dynamique
service quagga start


#Filtrage: Refuser tous les traffics
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#Autorisations 

#ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# RIP routing
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT


#DNS
iptables -t filter -A FORWARD -d 200.2.255.194/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 200.2.255.194/26 -p udp --sport 53 -j ACCEPT

# HTTP
iptables -t filter -A FORWARD -d 200.2.255.195/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 200.2.255.195/26 -p tcp --sport 80 -j ACCEPT

#FTP
iptables -A FORWARD -d 200.2.255.196/26 -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -s 200.2.255.196/26 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024: --dport 1024: -j ACCEPT


